### ISSUE TITLE
fnc `who_can_merge_pr` fails with traceback

### ISSUE THREAD

**Issue by phracek** [packit-service/ogr#132]
In `packit-service`, I am using method `who_can_merge_pr` for getting users who can merge PR.

* `get_owners` for repository `packit-service/packit-service` returns list `['packit-service']`
```
[2019-07-22 08:52:07,528: DEBUG/ForkPoolWorker-1] Repository owners ['packit-service']
```
* `who_can_merge_pr` for repository `rebase-helper/rebase-helper` returns list like `{'FrNecas', 'uhliarik', 'phracek', 'nforro', 'thozza'}` but for `packit-service/packit-service` repo it failed with traceback

```
[2019-07-22 08:52:08,368: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[9c44c1c8-5cf7-4a98-88d5-b0dbaca0262f] raised unexpected: AttributeError("'Repository' object has no attribute 'get_collaborator_permission'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 31, in process_message
    return SteveJobs().process_message(event=event, topic=topic)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 383, in process_message
    jobs_results = self.process_jobs(trigger, package_config, event, project)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 341, in process_jobs
    handlers_results[job.job.value] = handler.run()
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 793, in run
    return self.handle_pull_request()
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 717, in handle_pull_request
    collaborators = self.project.who_can_merge_pr()
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github.py", line 254, in who_can_merge_pr
    collaborators = self._get_collaborators_with_permission()
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github.py", line 294, in _get_collaborators_with_permission
    permission = self.github_repo.get_collaborator_permission(user)
AttributeError: 'Repository' object has no attribute 'get_collaborator_permission'
```

Function GITHUB API function which gets all collaborators returns
```
[2019-07-22 08:52:08,136: DEBUG/ForkPoolWorker-1] GET https://api.github.com/repos/packit-service/hello-world/collaborators 
{'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} None ==> 200 {'date': 'Mon, 22 Jul 2019 08:52:05 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '9897', 'server': 'GitHub.com', 'status': '200 OK', 'x-ratelimit-limit': '5000', 'x-ratelimit-remaining': '4997', 'x-ratelimit-reset': '1563789120', 'cache-control': 'private, max-age=60, s-maxage=60', 'vary': 'Accept-Encoding', 'etag': '"608e280b2b2bc2d96b1393ce9c294cee"', 'x-github-media-type': 'github.v3; format=json', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'content-security-policy': "default-src 'none'", 'x-github-request-id': '1110:253E:289043:3B0BB6:5D357935'}b'[
{"login":"jpopelka","id":288686,"node_id":"MDQ6VXNlcjI4ODY4Ng==","avatar_url":"https://avatars0.githubusercontent.com/u/288686?v=4","gravatar_id":"","url":"https://api.github.com/users/jpopelka","html_url":"https://github.com/jpopelka","followers_url":"https://api.github.com/users/jpopelka/followers","following_url":"https://api.github.com/users/jpopelka/following{/other_user}","gists_url":"https://api.github.com/users/jpopelka/gists{/gist_id}","starred_url":"https://api.github.com/users/jpopelka/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jpopelka/subscriptions","organizations_url":"https://api.github.com/users/jpopelka/orgs","repos_url":"https://api.github.com/users/jpopelka/repos","events_url":"https://api.github.com/users /jpopelka/events{/privacy}","received_events_url":"https://api.github.com/users/jpopelka/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"TomasTomecek","id":1662493,"node_id":"MDQ6VXNlcjE2NjI0OTM=","avatar_url":"https://avatars0.githubusercontent.com/u/1662493?v=4","gravatar_id":"","url":"https://api.github.com/users/TomasTomecek","html_url":"https://github.com/TomasTomecek","followers_url":"https://api.github.com/users/TomasTomecek/followers","following_url":"https://api.github.com/users/TomasTomecek/following{/other_user}","gists_url":"https://api.github.com/users/TomasTomecek/gists{/gist_id}","starred_url":"https://api.github.com/users/TomasTomecek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/TomasTomecek/subscriptions","organizations_url":"https://api.github.com/users/TomasTomecek/orgs","repos_url":"https://api.github.com/users/TomasTomecek/repos","events_url":"https://api.github.com/users/TomasTomecek/events{/privacy}","received_events_url":"https://api.github.com/users/TomasTomecek/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"eliskasl","id":1866652,"node_id":"MDQ6VXNlcjE4NjY2NTI=","avatar_url":"https://avatars3.githubusercontent.com/u/1866652?v=4","gravatar_id":"","url":"https://api.github.com/users/eliskasl","html_url":"https://github.com/eliskasl","followers_url":"https://api.github.com/users/eliskasl/followers","following_url":"https://api.github.com/users/eliskasl/following{/other_user}","gists_url":"https://api.github.com/users/eliskasl/gists{/gist_id}","starred_url":"https://api.github.com/users/eliskasl/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/eliskasl/subscriptions","organizations_url":"https://api.github.com/users/eliskasl/orgs","repos_url":"https://api.github.com/users/eliskasl/repos","events_url":"https://api.github.com/users/eliskasl/events{/privacy}","received_events_url":"https://api.github.com/users/ eliskasl/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"phracek","id":3416672,"node_id":"MDQ6VXNlcjM0MTY2NzI=","avatar_url":"https://avatars2.githubusercontent.com/u/3416672?v=4","gravatar_id":"","url":"https://api.github.com/users/phracek","html_url":"https://github.com/phracek","followers_url":"https://api.github.com/users/phracek/followers","following_url":"https://api.github.com/users/phracek/following{/other_user}","gists_url":"https://api.github.com/users/phracek/gists{/gist_id}","starred_url":"https://api.github.com/users/phracek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/phracek/subscriptions","organizations_url":"https://api.github.com/users/phracek/orgs","repos_url":"https://api.github.com/users/phracek/repos","events_url":"https://api.github.com/users/phracek/events{/privacy}","received_events_url":"https://api.github.com/users/phracek/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"jscotka","id":8735467,"node_id":"MDQ6VXNlcjg3MzU0Njc=","avatar_url":"https://avatars0.githubusercontent.com/u/8735467?v=4","gravatar_id":"","url":"https://api.github.com/users/jscotka","html_url":"https://github.com/jscotka","followers_url":"https://api.github.com/users/jscotka/followers","following_url":"https://api.github.com/users/jscotka/following{/other_user}","gists_url":"https://api.github.com/users/jscotka/gists{/gist_id}","starred_url":"https://api.github.com/users/jscotka/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jscotka/subscriptions","organizations_url":"https://api.github.com/users/jscotka/orgs","repos_url":"https://api.github.com/users/jscotka/repos","events_url":"https://api.github.com/users/jscotka/events{/privacy}","received_events_url":"https://api.github.com/users/jscotka/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},{"login":"lachmanfrantisek","id":202140 43,"node_id":"MDQ6VXNlcjIwMjE0MDQz","avatar_url":"https://avatars1.githubusercontent.com/u/20214043?v=4","gravatar_id":"","url":"https://api.github.com/users/lachmanfrantisek","html_url":"https://github.com/lachmanfrantisek","followers_url":"https://api.github.com/users/lachmanfrantisek/followers","following_url":"https://api.github.com/users/lachmanfrantisek/following{/other_user}","gists_url":"https://api.github.com/users/lachmanfrantisek/gists{/gist_id}","starred_url":"https://api.github.com/users/lachmanfrantisek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lachmanfrantisek/subscriptions","organizations_url":"https://api.github.com/users/lachmanfrantisek/orgs","repos_url":"https://api.github.com/users/lachmanfrantisek/repos","events_url":"https://api.github.com/users/lachmanfrantisek/events{/privacy}","received_events_url":"https://api.github.com/users/lachmanfrantisek/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"rpitonak","id":26160778,"node_id":"MDQ6VXNlcjI2MTYwNzc4","avatar_url":"https://avatars3.githubusercontent.com/u/26160778?v=4","gravatar_id":"","url":"https://api.github.com/users/rpitonak","html_url":"https://github.com/rpitonak","followers_url":"https://api.github.com/users/rpitonak/followers","following_url":"https://api.github.com/users/rpitonak/following{/other_user}","gists_url":"https://api.github.com/users/rpitonak/gists{/gist_id}","starred_url":"https://api.github.com/users/rpitonak/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rpitonak/subscriptions","organizations_url":"https://api.github.com/users/rpitonak/orgs","repos_url":"https://api.github.com/users/rpitonak/repos","events_url":"https://api.github.com/users/rpitonak/events{/privacy}","received_events_url":"https://api.github.com/users/rpitonak/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"dhodovsk","id":31201372,"node_id":"MDQ6VXNlcjMxMjAxMzcy ","avatar_url":"https://avatars2.githubusercontent.com/u/31201372?v=4","gravatar_id":"","url":"https://api.github.com/users/dhodovsk","html_url":"https://github.com/dhodovsk","followers_url":"https://api.github.com/users/dhodovsk/followers","following_url":"https://api.github.com/users/dhodovsk/following{/other_user}","gists_url":"https://api.github.com/users/dhodovsk/gists{/gist_id}","starred_url":"https://api.github.com/users/dhodovsk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dhodovsk/subscriptions","organizations_url":"https://api.github.com/users/dhodovsk/orgs","repos_url":"https://api.github.com/users/dhodovsk/repos","events_url":"https://api.github.com/users/dhodovsk/events{/privacy}","received_events_url":"https://api.github.com/users/dhodovsk/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"usercont-release-bot","id":36231209,"node_id":"MDQ6VXNlcjM2MjMxMjA5","avatar_url":"https://avatars1.githubusercontent.com/u/36231209?v=4","gravatar_id":"","url":"https://api.github.com/users/usercont-release-bot","html_url":"https://github.com/usercont-release-bot","followers_url":"https://api.github.com/users/usercont-release-bot/followers","following_url":"https://api.github.com/users/usercont-release-bot/following{/other_user}","gists_url":"https://api.github.com/users/usercont-release-bot/gists{/gist_id}","starred_url":"https://api.github.com/users/usercont-release-bot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/usercont-release-bot/subscriptions","organizations_url":"https://api.github.com/users/usercont-release-bot/orgs","repos_url":"https://api.github.com/users/usercont-release-bot/repos","events_url":"https://api.github.com/users/usercont-release-bot/events{/privacy}","received_events_url":"https://api.github.com/users/usercont-release-bot/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}},
{"login":"lbarcziova","id":49026743,"node_id": "MDQ6VXNlcjQ5MDI2NzQz","avatar_url":"https://avatars3.githubusercontent.com/u/49026743?v=4","gravatar_id":"","url":"https://api.github.com/users/lbarcziova","html_url":"https://github.com/lbarcziova","followers_url":"https://api.github.com/users/lbarcziova/followers","following_url":"https://api.github.com/users/lbarcziova/following{/other_user}","gists_url":"https://api.github.com/users/lbarcziova/gists{/gist_id}","starred_url":"https://api.github.com/users/lbarcziova/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lbarcziova/subscriptions","organizations_url":"https://api.github.com/users/lbarcziova/orgs","repos_url":"https://api.github.com/users/lbarcziova/repos","events_url":"https://api.github.com/users/lbarcziova/events{/privacy}","received_events_url":"https://api.github.com/users/lbarcziova/received_events","type":"User","site_admin":false,"permissions":{"admin":true,"push":true,"pull":true}}]'
```

**Comment by phracek** [comment]
After some analyses, I have found a problem.
Function `get_collaborator_permission` was added by commit https://github.com/PyGithub/PyGithub/pull/881
which was merged 27 Aug 2018 and released with version PyGithub (1.43) (https://github.com/PyGithub/PyGithub/releases/tag/v1.43)
In my `packit-service` container I have 
```
bash-4.4$ pip3 list | grep PyGithub
PyGithub                   1.39
bash-4.4$
```
I would add dependency into PyGithub >= 1.43
I will test it and let you know if it works.
Pull Request will follow up.

**Comment by phracek** [comment]
With the latest version of PyGithub all works properly.
See logs
```
[2019-07-22 10:59:05,684: DEBUG/ForkPoolWorker-1] Collaborators {'phracek', 'dhodovsk', 'lbarcziova', 'eliskasl', 'jscotka', 'rpitonak', 'lachmanfrantisek', 'usercont-release-bot', 'jpopelka', 'TomasTomecek'}
```

**Comment by TomasTomecek** [comment]
Seems like no one updated python-pygithub in Fedora for quite some time: https://koji.fedoraproject.org/koji/packageinfo?packageID=16053
