### ISSUE TITLE
GitHub check descriptions can only be 140 chars long

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#143]
```
Traceback (most recent call last):                                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task                                                                                 
    R = retval = fun(*args, **kwargs)                                                                                                                                        
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__                                                                         
    return self.run(*args, **kwargs)                                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 42, in process_message                                                                  
    return SteveJobs().process_message(event=event, topic=topic)                                                                                                             
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 126, in process_message                                                                  
    jobs_results = self.process_jobs(event_object)                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 92, in process_jobs                                                                      
    handlers_results[job.job.value] = handler.run()                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/github_handlers.py", line 330, in run                                                                   
    return self.handle_pull_request()                                                                                                                                        
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/github_handlers.py", line 305, in handle_pull_request                                                   
    r.report("failure", msg)
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/handler.py", line 84, in report
    self.commit_sha, state, url, description, check_name
  File "/usr/local/lib/python3.7/site-packages/ogr/read_only.py", line 68, in readonly_func
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github.py", line 541, in set_commit_status
    github_commit.create_status(state, target_url, description, context)
  File "/usr/local/lib/python3.7/site-packages/github/Commit.py", line 189, in create_status
    input=post_parameters
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {'message': 'Validation Failed', 'errors': [{'resource': 'Status', 'code': 'custom', 'field': 'description', 'message': 'descript
ion is too long (maximum is 140 characters)'}], 'documentation_url': 'https://developer.github.com/v3/repos/statuses/#create-a-status'}
```

**Comment by TomasTomecek** [comment]
can we prio this over the gitlab work?

**Comment by lachmanfrantisek** [comment]
> can we prio this over the gitlab work?

Sure!
