### ISSUE TITLE
[get_service_class_or_none()] TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jpopelka** [packit-service/ogr#261]
Seeing this on prod:

```
  | [2019-10-29 08:25:38,794: INFO/MainProcess] Received task: task.steve_jobs.process_message[9b4d1ddc-72e3-4bd8-8ff9-fb2cf96d8efb]
  | [2019-10-29 08:25:38,810: INFO/ForkPoolWorker-1] Copr build event, topic: org.fedoraproject.prod.copr.build.start
  | [2019-10-29 08:25:38,812: WARNING/ForkPoolWorker-1] Cannot get project for this build id: 1081435
  | [2019-10-29 08:25:38,819: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[9b4d1ddc-72e3-4bd8-8ff9-fb2cf96d8efb] raised unexpected: TypeError("argument of type 'NoneType' is not iterable")
  | Traceback (most recent call last):
  | File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
  | return self.run(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 155, in _inner
  | reraise(*exc_info)
  | File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
  | raise value
  | File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 150, in _inner
  | return f(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 47, in process_message
  | return SteveJobs().process_message(event=event, topic=topic)
  | File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 218, in process_message
  | project
  | File "/usr/local/lib/python3.7/site-packages/packit/config.py", line 212, in _get_project
  | project = get_project(url=url, custom_instances=self.services)
  | File "/usr/local/lib/python3.7/site-packages/ogr/factory.py", line 83, in get_project
  | kls = get_service_class(url=url, service_mapping_update=service_mapping_update)
  | File "/usr/local/lib/python3.7/site-packages/ogr/factory.py", line 135, in get_service_class
  | url=url, service_mapping_update=service_mapping_update
  | File "/usr/local/lib/python3.7/site-packages/ogr/factory.py", line 118, in get_service_class_or_none
  | if service in url:
  | TypeError: argument of type 'NoneType' is not iterable
```

**Comment by lachmanfrantisek** [comment]
The `get_service_class_or_none` requires non-None `url` argument:
https://github.com/packit-service/ogr/blob/master/ogr/factory.py#L103

(The problem is in the code before the function call.)

**Comment by lachmanfrantisek** [comment]
Can we close this or transfer to packit/packit-service?
